"""
Donation file structure data for takeout flows

This file contains a list of Entries for each platform.
Each Entry represents a table to be generated from the appropriate file.

To generate this file, please run structure/flow_generation/generate_entries.py
which will use the Merged_structures_*.csv to determine the required entries.
"""

from port.helpers.parsers import Entry

X_ENTRIES: list[Entry] = [
    Entry(table='account', filename='account.js', static_fields={'email': ('account', 'email'), 'createdVia': ('account', 'createdVia'), 'username': ('account', 'username'), 'accountId': ('account', 'accountId'), 'createdAt': ('account', 'createdAt'), 'accountDisplayName': ('account', 'accountDisplayName')}, list_blocks={}),
    Entry(table='account-creation-ip', filename='account-creation-ip.js', static_fields={'accountId': ('accountCreationIp', 'accountId'), 'userCreationIp': ('accountCreationIp', 'userCreationIp')}, list_blocks={}),
    Entry(table='account-label', filename='account-label.js', static_fields={'accountLabel': ('accountLabel',)}, list_blocks={}),
    Entry(table='account-timezone', filename='account-timezone.js', static_fields={'accountId': ('accountTimezone', 'accountId')}, list_blocks={}),
    Entry(table='ad-engagements', filename='ad-engagements.js', static_fields={'osType': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'deviceInfo', 'osType'), 'deviceId': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'deviceInfo', 'deviceId'), 'displayLocation': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'displayLocation'), 'tweetId': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'promotedTweetInfo', 'tweetId'), 'tweetText': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'promotedTweetInfo', 'tweetText'), 'advertiserName': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'advertiserInfo', 'advertiserName'), 'screenName': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'publisherInfo', 'screenName'), 'targetingType': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'matchedTargetingCriteria', 'targetingType'), 'targetingValue': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'matchedTargetingCriteria', 'targetingValue'), 'impressionTime': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'impressionTime'), 'engagementTime': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'engagementAttributes', 'engagementTime'), 'engagementType': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'engagementAttributes', 'engagementType'), 'trendId': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'promotedTrendInfo', 'trendId'), 'name': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'promotedTrendInfo', 'name'), 'description': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'promotedTrendInfo', 'description'), 'publisherName': ('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'publisherInfo', 'publisherName')}, list_blocks={('ad', 'adsUserData', 'adEngagements', 'engagements', 'impressionAttributes', 'promotedTweetInfo'): {'mediaUrls': ('mediaUrls',), 'urls': ('urls',)}}),
    Entry(table='ageinfo', filename='ageinfo.js', static_fields={'birthDate': ('ageMeta', 'ageInfo', 'birthDate')}, list_blocks={('ageMeta', 'ageInfo'): {'age': ('age',)}}),
    Entry(table='community-note-rating', filename='community-note-rating.js', static_fields={'noteId': ('communityNoteRating', 'noteId'), 'helpfulnessLevel': ('communityNoteRating', 'helpfulnessLevel'), 'createdAt': ('communityNoteRating', 'createdAt'), 'userId': ('communityNoteRating', 'userId')}, list_blocks={('communityNoteRating',): {'helpfulTags': ('helpfulTags',)}}),
    Entry(table='connected-application', filename='connected-application.js', static_fields={'name': ('connectedApplication', 'name'), 'url': ('connectedApplication', 'organization', 'url'), 'description': ('connectedApplication', 'description'), 'approvedAt': ('connectedApplication', 'approvedAt'), 'id': ('connectedApplication', 'id'), 'privacyPolicyUrl': ('connectedApplication', 'organization', 'privacyPolicyUrl'), 'termsAndConditionsUrl': ('connectedApplication', 'organization', 'termsAndConditionsUrl')}, list_blocks={('connectedApplication',): {'permissions': ('permissions',)}}),
    Entry(table='device-token', filename='device-token.js', static_fields={'clientApplicationId': ('deviceToken', 'clientApplicationId'), 'token': ('deviceToken', 'token'), 'createdAt': ('deviceToken', 'createdAt'), 'lastSeenAt': ('deviceToken', 'lastSeenAt'), 'clientApplicationName': ('deviceToken', 'clientApplicationName')}, list_blocks={}),
    Entry(table='direct-message-group-headers', filename='direct-message-group-headers.js', static_fields={'conversationId': ('dmConversation', 'conversationId'), 'id': ('dmConversation', 'messages', 'messageCreate', 'id'), 'senderId': ('dmConversation', 'messages', 'messageCreate', 'senderId'), 'createdAt': ('dmConversation', 'messages', 'joinConversation', 'createdAt'), 'initiatingUserId': ('dmConversation', 'messages', 'joinConversation', 'initiatingUserId')}, list_blocks={('dmConversation', 'messages', 'joinConversation'): {'participantsSnapshot': ('participantsSnapshot',)}}),
    Entry(table='direct-message-headers', filename='direct-message-headers.js', static_fields={'conversationId': ('dmConversation', 'conversationId'), 'id': ('dmConversation', 'messages', 'messageCreate', 'id'), 'senderId': ('dmConversation', 'messages', 'messageCreate', 'senderId'), 'recipientId': ('dmConversation', 'messages', 'messageCreate', 'recipientId'), 'createdAt': ('dmConversation', 'messages', 'messageCreate', 'createdAt')}, list_blocks={}),
    Entry(table='direct-messages', filename='direct-messages.js', static_fields={'conversationId': ('dmConversation', 'conversationId'), 'recipientId': ('dmConversation', 'messages', 'messageCreate', 'recipientId'), 'text': ('dmConversation', 'messages', 'messageCreate', 'text'), 'senderId': ('dmConversation', 'messages', 'messageCreate', 'reactions', 'senderId'), 'id': ('dmConversation', 'messages', 'messageCreate', 'id'), 'createdAt': ('dmConversation', 'messages', 'messageCreate', 'reactions', 'createdAt'), 'url': ('dmConversation', 'messages', 'messageCreate', 'urls', 'url'), 'expanded': ('dmConversation', 'messages', 'messageCreate', 'urls', 'expanded'), 'display': ('dmConversation', 'messages', 'messageCreate', 'urls', 'display'), 'reactionKey': ('dmConversation', 'messages', 'messageCreate', 'reactions', 'reactionKey'), 'eventId': ('dmConversation', 'messages', 'messageCreate', 'reactions', 'eventId')}, list_blocks={('dmConversation', 'messages', 'messageCreate'): {'mediaUrls': ('mediaUrls',)}}),
    Entry(table='direct-messages-group', filename='direct-messages-group.js', static_fields={'conversationId': ('dmConversation', 'conversationId'), 'url': ('dmConversation', 'messages', 'messageCreate', 'urls', 'url'), 'expanded': ('dmConversation', 'messages', 'messageCreate', 'urls', 'expanded'), 'display': ('dmConversation', 'messages', 'messageCreate', 'urls', 'display'), 'text': ('dmConversation', 'messages', 'messageCreate', 'text'), 'senderId': ('dmConversation', 'messages', 'messageCreate', 'reactions', 'senderId'), 'id': ('dmConversation', 'messages', 'messageCreate', 'id'), 'createdAt': ('dmConversation', 'messages', 'joinConversation', 'createdAt'), 'reactionKey': ('dmConversation', 'messages', 'messageCreate', 'reactions', 'reactionKey'), 'eventId': ('dmConversation', 'messages', 'messageCreate', 'reactions', 'eventId'), 'initiatingUserId': ('dmConversation', 'messages', 'joinConversation', 'initiatingUserId')}, list_blocks={('dmConversation', 'messages', 'joinConversation'): {'participantsSnapshot': ('participantsSnapshot',)}}),
    Entry(table='email-address-change', filename='email-address-change.js', static_fields={'accountId': ('emailAddressChange', 'accountId'), 'changedAt': ('emailAddressChange', 'emailChange', 'changedAt'), 'changedTo': ('emailAddressChange', 'emailChange', 'changedTo')}, list_blocks={}),
    Entry(table='expanded-profile', filename='expanded-profile.js', static_fields={'expandedProfile': ('expandedProfile',)}, list_blocks={}),
    Entry(table='follower', filename='follower.js', static_fields={'accountId': ('follower', 'accountId'), 'userLink': ('follower', 'userLink')}, list_blocks={}),
    Entry(table='following', filename='following.js', static_fields={'accountId': ('following', 'accountId'), 'userLink': ('following', 'userLink')}, list_blocks={}),
    Entry(table='ip-audit', filename='ip-audit.js', static_fields={'accountId': ('ipAudit', 'accountId'), 'createdAt': ('ipAudit', 'createdAt'), 'loginIp': ('ipAudit', 'loginIp'), 'loginPortNumber': ('ipAudit', 'loginPortNumber')}, list_blocks={}),
    Entry(table='key-registry', filename='key-registry.js', static_fields={'userId': ('keyRegistryData', 'userId'), 'userAgent': ('keyRegistryData', 'registeredDevices', 'deviceMetadataList', 'userAgent'), 'registrationToken': ('keyRegistryData', 'registeredDevices', 'deviceMetadataList', 'registrationToken'), 'identityKey': ('keyRegistryData', 'registeredDevices', 'deviceMetadataList', 'identityKey'), 'createdAt': ('keyRegistryData', 'registeredDevices', 'deviceMetadataList', 'createdAt'), 'deviceId': ('keyRegistryData', 'registeredDevices', 'deviceMetadataList', 'deviceId')}, list_blocks={}),
    Entry(table='like', filename='like.js', static_fields={'tweetId': ('like', 'tweetId'), 'fullText': ('like', 'fullText'), 'expandedUrl': ('like', 'expandedUrl')}, list_blocks={}),
    Entry(table='lists-created', filename='lists-created.js', static_fields={'url': ('userListInfo', 'url')}, list_blocks={}),
    Entry(table='lists-member', filename='lists-member.js', static_fields={'url': ('userListInfo', 'url')}, list_blocks={}),
    Entry(table='lists-subscribed', filename='lists-subscribed.js', static_fields={'url': ('userListInfo', 'url')}, list_blocks={}),
    Entry(table='manifest', filename='manifest.js', static_fields={'accountId': ('userInfo', 'accountId'), 'userName': ('userInfo', 'userName'), 'displayName': ('userInfo', 'displayName'), 'sizeBytes': ('archiveInfo', 'sizeBytes'), 'generationDate': ('archiveInfo', 'generationDate'), 'isPartialArchive': ('archiveInfo', 'isPartialArchive'), 'maxPartSizeBytes': ('archiveInfo', 'maxPartSizeBytes'), 'fileName': ('dataTypes', 'verifiedOrganization', 'files', 'fileName'), 'directory': ('readmeInfo', 'directory'), 'name': ('readmeInfo', 'name'), 'globalName': ('dataTypes', 'verifiedOrganization', 'files', 'globalName'), 'count': ('dataTypes', 'verifiedOrganization', 'files', 'count'), 'mediaDirectory': ('dataTypes', 'tweetsMedia', 'mediaDirectory')}, list_blocks={}),
    Entry(table='periscope-account-information', filename='periscope-account-information.js', static_fields={'displayName': ('periscopeAccountInformation', 'displayName'), 'digitsId': ('periscopeAccountInformation', 'digitsId'), 'username': ('periscopeAccountInformation', 'username'), 'twitterId': ('periscopeAccountInformation', 'twitterId'), 'id': ('periscopeAccountInformation', 'id'), 'twitterScreenName': ('periscopeAccountInformation', 'twitterScreenName'), 'isTwitterUser': ('periscopeAccountInformation', 'isTwitterUser'), 'createdAt': ('periscopeAccountInformation', 'createdAt')}, list_blocks={}),
    Entry(table='periscope-ban-information', filename='periscope-ban-information.js', static_fields={'periscopeBanInformation': ('periscopeBanInformation',)}, list_blocks={}),
    Entry(table='periscope-profile-description', filename='periscope-profile-description.js', static_fields={'bio': ('periscopeProfileDescription', 'bio')}, list_blocks={}),
    Entry(table='personalization', filename='personalization.js', static_fields={'language': ('p13nData', 'demographics', 'languages', 'language'), 'isDisabled': ('p13nData', 'interests', 'interests', 'isDisabled'), 'gender': ('p13nData', 'demographics', 'genderInfo', 'gender'), 'name': ('p13nData', 'interests', 'interests', 'name'), 'numAudiences': ('p13nData', 'interests', 'audienceAndAdvertisers', 'numAudiences'), 'birthDate': ('p13nData', 'inferredAgeInfo', 'birthDate')}, list_blocks={('p13nData', 'interests', 'audienceAndAdvertisers'): {'lookalikeAdvertisers': ('lookalikeAdvertisers',), 'advertisers': ('advertisers',)}, ('p13nData', 'interests'): {'shows': ('shows',)}, ('p13nData', 'inferredAgeInfo'): {'age': ('age',)}}),
    Entry(table='profile', filename='profile.js', static_fields={'bio': ('profile', 'description', 'bio'), 'website': ('profile', 'description', 'website'), 'location': ('profile', 'description', 'location'), 'avatarMediaUrl': ('profile', 'avatarMediaUrl'), 'headerMediaUrl': ('profile', 'headerMediaUrl')}, list_blocks={}),
    Entry(table='saved-search', filename='saved-search.js', static_fields={'savedSearchId': ('savedSearch', 'savedSearchId'), 'query': ('savedSearch', 'query')}, list_blocks={}),
    Entry(table='screen-name-change', filename='screen-name-change.js', static_fields={'accountId': ('screenNameChange', 'accountId'), 'changedAt': ('screenNameChange', 'screenNameChange', 'changedAt'), 'changedFrom': ('screenNameChange', 'screenNameChange', 'changedFrom'), 'changedTo': ('screenNameChange', 'screenNameChange', 'changedTo')}, list_blocks={}),
    Entry(table='tweet-headers', filename='tweet-headers.js', static_fields={'tweet_id': ('tweet', 'tweet_id'), 'user_id': ('tweet', 'user_id'), 'created_at': ('tweet', 'created_at')}, list_blocks={}),
    Entry(table='tweets', filename='tweets.js', static_fields={'editableUntil': ('tweet', 'edit_info', 'initial', 'editableUntil'), 'editsRemaining': ('tweet', 'edit_info', 'initial', 'editsRemaining'), 'isEditEligible': ('tweet', 'edit_info', 'initial', 'isEditEligible'), 'retweeted': ('tweet', 'retweeted'), 'source': ('tweet', 'source'), 'url': ('tweet', 'extended_entities', 'media', 'url'), 'expanded_url': ('tweet', 'extended_entities', 'media', 'expanded_url'), 'display_url': ('tweet', 'extended_entities', 'media', 'display_url'), 'favorite_count': ('tweet', 'favorite_count'), 'id_str': ('tweet', 'extended_entities', 'media', 'id_str'), 'truncated': ('tweet', 'truncated'), 'retweet_count': ('tweet', 'retweet_count'), 'id': ('tweet', 'extended_entities', 'media', 'id'), 'possibly_sensitive': ('tweet', 'possibly_sensitive'), 'created_at': ('tweet', 'created_at'), 'favorited': ('tweet', 'favorited'), 'full_text': ('tweet', 'full_text'), 'lang': ('tweet', 'lang'), 'name': ('tweet', 'entities', 'user_mentions', 'name'), 'screen_name': ('tweet', 'entities', 'user_mentions', 'screen_name'), 'in_reply_to_status_id_str': ('tweet', 'in_reply_to_status_id_str'), 'in_reply_to_user_id': ('tweet', 'in_reply_to_user_id'), 'in_reply_to_status_id': ('tweet', 'in_reply_to_status_id'), 'in_reply_to_screen_name': ('tweet', 'in_reply_to_screen_name'), 'in_reply_to_user_id_str': ('tweet', 'in_reply_to_user_id_str'), 'text': ('tweet', 'entities', 'hashtags', 'text'), 'media_url': ('tweet', 'extended_entities', 'media', 'media_url'), 'media_url_https': ('tweet', 'extended_entities', 'media', 'media_url_https'), 'w': ('tweet', 'extended_entities', 'media', 'sizes', 'thumb', 'w'), 'h': ('tweet', 'extended_entities', 'media', 'sizes', 'thumb', 'h'), 'resize': ('tweet', 'extended_entities', 'media', 'sizes', 'thumb', 'resize'), 'type': ('tweet', 'extended_entities', 'media', 'type'), 'source_status_id': ('tweet', 'extended_entities', 'media', 'source_status_id'), 'source_user_id': ('tweet', 'extended_entities', 'media', 'source_user_id'), 'source_user_id_str': ('tweet', 'extended_entities', 'media', 'source_user_id_str'), 'source_status_id_str': ('tweet', 'extended_entities', 'media', 'source_status_id_str')}, list_blocks={('tweet', 'edit_info', 'initial'): {'editTweetIds': ('editTweetIds',)}, ('tweet', 'entities', 'urls'): {'indices': ('indices',)}, ('tweet',): {'display_text_range': ('display_text_range',)}, ('tweet', 'entities', 'user_mentions'): {'indices': ('indices',)}, ('tweet', 'entities', 'hashtags'): {'indices': ('indices',)}, ('tweet', 'entities', 'media'): {'indices': ('indices',)}, ('tweet', 'extended_entities', 'media'): {'indices': ('indices',)}}),
    Entry(table='verified', filename='verified.js', static_fields={'accountId': ('verified', 'accountId'), 'verified': ('verified', 'verified')}, list_blocks={}),
    Entry(table='verified-organization', filename='verified-organization.js', static_fields={'verifiedOrganization': ('verifiedOrganization',)}, list_blocks={}),
]

